function render(){
  const app=document.querySelector('#app');
  app.innerHTML=`<div class="shell">${sidebar()}<main class="main"><div class="main-inner">${topbar()}${content()}</div></main>${mobileNav()}</div>${modalHtml()}`;
  wire();
}
function navButton(id,label){return `<button data-nav="${id}" class="${state.view===id?'active':''}"><span class="nav-icon">${navGlyph(id)}</span><span>${label}</span></button>`;}
function sidebar(){
  const saved=state.cases.length;
  return `<aside class="sidebar"><div class="brand"><div class="brand-mark">TF</div><div><strong>TraceForge</strong><small>McLain Systems</small></div></div><nav class="nav">${navButton('investigate','Investigate')}${navButton('cases','Cases')}${navButton('sources','Coverage')}</nav><div class="sidebar-status"><strong><span class="live-dot"></span> Evidence-first mode</strong><p>${saved} saved case${saved===1?'':'s'} on this device. Searches stay ephemeral until you explicitly save findings.</p></div></aside>`;
}
function mobileNav(){return `<nav class="mobile-nav">${navButton('investigate','Search')}${navButton('cases','Cases')}${navButton('sources','Coverage')}</nav>`;}
function topbar(){
  const titles={investigate:['Investigation console','Public-source checks with source-per-finding traceability.'],cases:['Case workspace','Preserve evidence, relationships, timeline and contradictions.'],sources:['Source coverage','See exactly what TraceForge can check and where coverage stops.']};
  const [t,s]=titles[state.view]||titles.investigate;
  return `<header class="topbar"><div><div class="eyebrow">TraceForge / McLain Systems</div><h1>${t}</h1><p class="muted small">${s}</p></div><div class="actions no-print"><button class="btn ghost small" data-clear-session>Clear session</button></div></header>`;
}
function content(){if(state.view==='cases')return casesView();if(state.view==='sources')return sourcesView();return investigateView();}
function providerGlyph(id){return ({github:'GH',gitlab:'GL',dns:'DNS',rdap:'RD',rdapip:'RD',ripe:'ASN',history:'HIS',hibp:'BR',phone:'TEL',hash:'HASH',research:'RCH'})[id]||'SRC';}
function sessionStats(){
  const entries=Object.values(state.providers);
  return {total:entries.length,loaded:entries.filter(p=>!['idle','loading'].includes(p.status)).length,good:entries.filter(p=>p.status==='success').length,findings:allFindings().length,issues:entries.filter(p=>['error','timeout'].includes(p.status)).length};
}
function capabilityCards(){
  return `<div class="capability-grid"><div class="capability"><div class="capability-icon">@</div><h3>Username</h3><p>Exact-handle checks plus broader public account pivots.</p><span class="badge teal">identity lead</span></div><div class="capability"><div class="capability-icon">DNS</div><h3>Email / domain / URL</h3><p>DNS, RDAP, certificate history and archived-web context.</p><span class="badge blue">live + history</span></div><div class="capability"><div class="capability-icon">IP</div><h3>IP address</h3><p>Routing, ASN and registry allocation without person attribution.</p><span class="badge blue">network</span></div><div class="capability"><div class="capability-icon">#</div><h3>Hash</h3><p>Recognize MD5, SHA-1 and SHA-256 and route to threat-triage sources.</p><span class="badge warn">pivot</span></div><div class="capability"><div class="capability-icon">TEL</div><h3>Phone</h3><p>Normalize and route to vetted public pivots without automatic owner claims.</p><span class="badge warn">review-first</span></div><div class="capability"><div class="capability-icon">ABC</div><h3>Person / company / topic</h3><p>Choose a research lane and get a deterministic public-source playbook.</p><span class="badge teal">research lane</span></div></div>`;
}

function investigateView(){
  const meta=state.queryMeta,pEntries=Object.values(state.providers),stats=sessionStats();
  return `<section class="section"><div class="hero"><div class="hero-copy"><div class="eyebrow">PUBLIC-SOURCE INTELLIGENCE WORKSPACE</div><h2>Search an identifier. Keep only what the source can prove.</h2><p>TraceForge checks supported public sources independently, shows gaps instead of inventing conclusions, and lets you preserve selected findings into an auditable case.</p></div><div class="search-shell"><input id="searchInput" class="search" value="${esc(state.query)}" placeholder="email, username, domain, URL, IP, phone, hash, person, company…" autocomplete="off" autocapitalize="none" spellcheck="false"><button class="btn primary" id="searchBtn">${pEntries.some(p=>p.status==='loading')?'Checking…':'Run trace'}</button></div><div class="search-examples"><button class="search-example" data-example="github">username example</button><button class="search-example" data-example="example.com">domain example</button><button class="search-example" data-example="1.1.1.1">IP example</button><button class="search-example" data-example="company: OpenAI">research example</button></div>${meta?`<div class="search-meta"><span class="badge ${meta.valid?'teal':'error'}">${esc(meta.label)}</span>${meta.valid?`<span class="small muted">${esc(meta.normalized)}</span>`:''}</div>`:''}</div></section>
  ${pEntries.length?`<section class="section"><div class="stats-row"><div class="stat"><span>Sources</span><strong>${stats.total}</strong><small>${stats.loaded} finished</small></div><div class="stat"><span>Fetched</span><strong>${stats.good}</strong><small>successful providers</small></div><div class="stat"><span>Findings</span><strong>${stats.findings}</strong><small>source-backed lines</small></div><div class="stat"><span>Errors</span><strong>${stats.issues}</strong><small>visible, never hidden</small></div></div></section><section class="section"><div class="result-toolbar"><div><strong>${stats.findings?`${stats.findings} finding${stats.findings===1?'':'s'} ready to review`:'No source-backed finding yet'}</strong><div class="small muted">Select only the lines you want preserved as evidence.</div></div>${stats.findings?`<div class="actions"><button class="btn ghost small" data-select-all>Select all</button><button class="btn primary small" data-save-selected>Save selected</button></div>`:''}</div><div class="provider-list">${pEntries.map(providerHtml).join('')}</div></section>`:`<section class="section"><div class="section-head"><div><h2>What this build can inspect</h2><p class="muted small">Start with one identifier. TraceForge routes it only to applicable sources.</p></div></div>${capabilityCards()}</section><section class="section"><div class="card inset"><strong>Evidence rule</strong><p class="small muted" style="margin-bottom:0">A result is not an identity claim. Every fetched line keeps its provider, source URL, check time and limitation.</p></div></section>`}`;
}
function statusBadge(p){const m={loading:['teal','Checking'],success:['ok','Fetched'],['no-match']:['warn','No match'],error:['error','Error'],timeout:['error','Timeout'],unsupported:['warn','Unavailable'],idle:['','Queued']};const [c,l]=m[p.status]||['',p.status];return `<span class="badge ${c}"><span class="status-dot"></span>${l}</span>`;}
function providerScope(id){return ({github:'public developer profile',gitlab:'public developer profile',dns:'public DNS records',rdap:'domain registration registry',rdapip:'IP registry allocation',ripe:'routing and ASN context',history:'certificate transparency + web archive',hibp:'breach provider',phone:'public phone pivots',hash:'threat-reputation pivots',research:'research routing'})[id]||'public source';}
function providerHtml(p){return `<article class="provider" data-status="${esc(p.status)}"><div class="provider-head"><div class="provider-title"><div class="provider-glyph">${providerGlyph(p.id)}</div><div><h3>${esc(p.name)}</h3><div class="small muted">${providerScope(p.id)}</div></div></div><div class="actions">${statusBadge(p)}${['error','timeout','no-match'].includes(p.status)&&['github','gitlab','dns','rdap','history','rdapip','ripe'].includes(p.id)?`<button class="btn small ghost" data-retry="${p.id}">Retry</button>`:''}</div></div>${p.note?`<div class="notice warn">${esc(p.note)}</div>`:''}${p.error?`<div class="notice danger">${esc(p.error)}</div>`:''}${p.status==='no-match'?`<div class="notice">This provider returned no matching result. That is not proof the identifier is unused elsewhere.</div>`:''}${p.findings?.length?p.findings.map(findingHtml).join(''):''}</article>`;}
function findingHtml(f){return `<div class="checkline"><input aria-label="Select finding" type="checkbox" data-finding-check="${f.id}" ${state.selectedFindingIds.has(f.id)?'checked':''}><div class="finding"><p>${esc(f.observation)}</p><div class="finding-meta"><span>${esc(f.provider)}</span><span>${esc(fmtDate(f.checkedAt))}</span><a href="${esc(f.url)}" target="_blank" rel="noopener noreferrer">Open source</a></div><div class="small muted">Limit: ${esc(f.limitation)}</div></div></div>`;}

