function caseBriefStats(c){
  const providers=[...new Set(c.evidence.map(e=>e.provider||e.provenance).filter(Boolean))];
  const strengths=c.evidence.reduce((m,e)=>{const k=evidenceStrength(e).label;m[k]=(m[k]||0)+1;return m;},{});
  return {providers,strengths,open:c.questions.filter(q=>!q.resolved),dated:c.evidence.filter(e=>e.sourceEventDate).length,gaps:gapSuggestions(c)};
}
function briefTab(c){
  const s=caseBriefStats(c);
  const strengthRows=Object.entries(s.strengths).sort((a,b)=>b[1]-a[1]);
  return `<div class="grid two"><div class="card"><div class="eyebrow">CASE SNAPSHOT</div><h3>What is actually in this case</h3><div class="stats-row brief-stats"><div class="stat"><span>Evidence</span><strong>${c.evidence.length}</strong><small>${s.dated} dated</small></div><div class="stat"><span>Sources</span><strong>${s.providers.length}</strong><small>provider families</small></div><div class="stat"><span>Entities</span><strong>${c.entities.length}</strong><small>${c.relations.length} relationships</small></div><div class="stat"><span>Open work</span><strong>${s.open.length}</strong><small>questions/tasks</small></div></div><div class="brief-block"><strong>Evidence strength</strong><div class="tagline">${strengthRows.length?strengthRows.map(([k,n])=>`<span class="badge">${esc(k)} · ${n}</span>`).join(''):'<span class="small muted">No evidence yet.</span>'}</div></div><div class="brief-block"><strong>Source diversity</strong><div class="tagline">${s.providers.length?s.providers.map(p=>`<span class="badge dark">${esc(p)}</span>`).join(''):'<span class="small muted">No sources yet.</span>'}</div></div></div><div class="card"><div class="eyebrow">PROOF GAPS</div><h3>What still needs work</h3>${s.gaps.length?`<ul class="brief-list">${s.gaps.map(g=>`<li>${esc(g)}</li>`).join('')}</ul>`:`<div class="notice">No structural gaps detected by the current deterministic rules.</div>`}<div class="brief-block"><strong>Open items</strong>${s.open.length?`<ul class="brief-list">${s.open.slice(0,8).map(q=>`<li><span class="badge ${q.type==='contradiction'?'error':q.type==='task'?'warn':'teal'}">${esc(q.type)}</span> ${esc(q.text)}</li>`).join('')}</ul>`:`<p class="small muted">Nothing open.</p>`}</div></div></div><div class="card"><div class="section-head"><div><h3>Portable case package</h3><p class="small muted">Keep the raw case, a human-readable brief, and a spreadsheet-ready ledger.</p></div><div class="actions"><button class="btn ghost" data-export-case>JSON</button><button class="btn ghost" data-export-md>Markdown</button><button class="btn ghost" data-export-csv>Evidence CSV</button><button class="btn primary" data-print>Print / PDF</button></div></div></div>`;
}
function casesView(){
  const c=currentCase();
  return `<section class="section"><div class="section-head"><div><h2>Saved cases</h2><p class="muted small">Saved on this device · not cloud synced.</p></div><div class="actions"><button class="btn primary" data-new-case>New case</button><label class="btn ghost" style="cursor:pointer">Import case JSON<input type="file" accept="application/json,.json" data-import-case hidden></label></div></div>${state.cases.length?`<div class="case-list">${state.cases.map(caseRow).join('')}</div>`:`<div class="empty">No cases saved yet. Searches remain ephemeral until you create one.</div>`}</section>
  ${c?caseWorkspace(c):''}
  <section class="section"><div class="card"><div class="section-head"><div><h3>Local data controls</h3><p class="small muted">Clear session does not touch saved cases. Delete all local data is permanent.</p></div><button class="btn danger" data-delete-all>Delete all local data</button></div></div></section>`;
}
function caseRow(c){return `<div class="case-row ${c.id===state.currentCaseId?'case-current':''}"><div><strong>${esc(c.name)}</strong><span class="small muted">${c.evidence.length} evidence · ${c.relations.length} connections · updated ${esc(fmtDate(c.updatedAt))}</span></div><div class="actions"><button class="btn small ${c.id===state.currentCaseId?'secondary':'ghost'}" data-open-case="${c.id}">${c.id===state.currentCaseId?'Open':'Open case'}</button><button class="btn small ghost" data-rename-case="${c.id}">Rename</button><button class="btn small danger" data-delete-case="${c.id}">Delete</button></div></div>`;}
function caseWorkspace(c){
  const tabs=[['brief','Brief'],['evidence','Evidence'],['connections','Connections'],['timeline','Timeline'],['questions','Questions']];
  return `<section class="section"><div class="card"><div class="section-head"><div><div class="eyebrow">Current case</div><h2>${esc(c.name)}</h2><p class="small muted">Saved on this device · not cloud synced · updated ${esc(fmtDate(c.updatedAt))}.</p></div><div class="actions no-print"><button class="btn ghost" data-export-case>JSON</button><button class="btn ghost" data-export-md>Markdown</button><button class="btn ghost" data-export-csv>CSV</button><button class="btn ghost" data-print>Print</button></div></div><div class="tabs">${tabs.map(([id,l])=>`<button class="${state.caseTab===id?'active':''}" data-case-tab="${id}">${l}</button>`).join('')}</div></div>${caseTabContent(c)}</section>`;
}function caseTabContent(c){
  if(state.caseTab==='brief')return briefTab(c);
  if(state.caseTab==='connections')return connectionsTab(c);
  if(state.caseTab==='timeline')return timelineTab(c);
  if(state.caseTab==='questions')return questionsTab(c);
  return evidenceTab(c);
}function evidenceTab(c){
 return `<div class="grid two"><div class="card"><h3>Add manual evidence</h3><p class="small muted">Every manual item keeps its user-supplied provenance. Event date is separate from retrieval time.</p><form id="manualEvidence" class="form-grid"><label>Title<input class="input" name="title" required></label><label>Subject / entity<input class="input" name="subject" required></label><label class="full">Exact observed claim / quotation<textarea name="observation" required></textarea></label><label>HTTPS source URL<input class="input" name="sourceUrl" inputmode="url" placeholder="https://…"></label><label>Original filename<input class="input" name="originalFilename" placeholder="document.txt"></label><label>Source event date<input class="input" type="date" name="sourceEventDate"></label><label>Status<select name="status"><option>observed</option><option>inferred</option><option>disputed</option></select></label><label class="full">Tags, comma separated<input class="input" name="tags"></label><label class="full">Notes<textarea name="notes"></textarea></label><div class="full actions"><button class="btn primary" type="submit">Save evidence</button></div></form></div>
 <div class="card"><h3>Import evidence</h3><p class="small muted">Paste text or import .txt, .json, .csv. PDF/OCR is not implemented.</p><textarea id="pasteImport" placeholder="Paste source text or JSON/CSV here…"></textarea><div class="actions" style="margin-top:10px"><button class="btn secondary" data-preview-paste>Preview pasted text</button><label class="btn ghost" style="cursor:pointer">Choose file<input type="file" data-evidence-file accept=".txt,.json,.csv,text/plain,application/json,text/csv" hidden></label></div>${state.importPreview?importPreviewHtml():''}</div></div>
 <div class="card"><div class="section-head"><div><h3>Evidence ledger</h3><p class="small muted">${c.evidence.length} item${c.evidence.length===1?'':'s'}</p></div></div>${c.evidence.length?`<div class="ledger">${c.evidence.map(evidenceRow).join('')}</div>`:`<div class="empty">No evidence saved in this case yet.</div>`}</div>`;
}
function importPreviewHtml(){const p=state.importPreview;return `<div class="notice" style="margin-top:12px"><strong>Preview: ${p.items.length} item${p.items.length===1?'':'s'}</strong><br>${p.items.slice(0,3).map(x=>esc(x.title)).join(' · ')}${p.items.length>3?' …':''}<div class="actions" style="margin-top:8px"><button class="btn small primary" data-commit-import>Commit import</button><button class="btn small ghost" data-cancel-import>Cancel</button></div></div>`;}
function evidenceRow(e){
  const s=evidenceStrength(e);
  return `<div class="evidence-row"><div><div class="actions"><span class="badge ${e.status==='disputed'?'error':e.status==='inferred'?'warn':'ok'}">${esc(e.status)}</span><span class="badge ${s.className}">${esc(s.label)}</span><span class="badge">${esc(e.provenance)}</span>${e.sourceEventDate?`<span class="badge teal">event ${esc(fmtDay(e.sourceEventDate))}</span>`:''}</div><h3 style="margin-top:8px">${esc(e.title)}</h3><p>${esc(e.observation)}</p><p class="small muted"><strong>${esc(e.subject)}</strong> · retrieved ${esc(fmtDate(e.retrievedAt))}</p><div class="tagline">${(e.tags||[]).map(t=>`<span class="badge">${esc(t)}</span>`).join('')}</div><p class="small">Source: ${e.sourceUrl?`<a href="${esc(e.sourceUrl)}" target="_blank" rel="noopener">${esc(e.sourceUrl)}</a>`:esc(e.originalFilename||'—')}</p>${e.notes?`<p class="small muted">Limit / notes: ${esc(e.notes)}</p>`:''}</div><div class="actions"><button class="btn small danger" data-delete-evidence="${e.id}">Delete</button></div></div>`;
}
