function connectionsTab(c){
 const entityOptions=c.entities.map(e=>`<option value="${e.id}">${esc(e.label)}</option>`).join(''),evOpts=c.evidence.map(e=>`<option value="${e.id}">${esc(e.title)}</option>`).join('');
 return `<div class="grid two"><div class="card"><h3>Entities</h3><form id="entityForm" class="form-grid"><label>Label<input class="input" name="label" required></label><label>Type<input class="input" name="type" placeholder="person, domain, account…"></label><div class="full"><button class="btn primary" type="submit">Add entity</button></div></form><div class="tagline" style="margin-top:14px">${c.entities.map(e=>`<span class="badge dark">${esc(e.label)} · ${esc(e.type||'entity')}</span>`).join('')||'<span class="muted small">Entities appear from saved evidence or manual entry.</span>'}</div></div><div class="card"><h3>Add relationship</h3><form id="relationForm" class="form-grid"><label>From<select name="fromId" required><option value="">Select…</option>${entityOptions}</select></label><label>To<select name="toId" required><option value="">Select…</option>${entityOptions}</select></label><label>Relationship label<input class="input" name="label" placeholder="controls, references, same organization…" required></label><label>Mode<select name="mode"><option value="observed">observed</option><option value="hypothesis">hypothesis</option></select></label><label class="full">Supporting evidence<select name="evidenceIds" multiple size="4">${evOpts}</select></label><div class="full"><button class="btn primary" type="submit">Add relationship</button></div></form></div></div><div class="card"><h3>Relationship list</h3><p class="small muted">Relationships are human-reviewed. Shared identifiers never auto-merge identities.</p>${c.relations.length?`<div class="relation-list">${c.relations.map(r=>relationRow(c,r)).join('')}</div>`:`<div class="empty">No relationships yet.</div>`}</div>`;
}
function relationRow(c,r){const f=c.entities.find(e=>e.id===r.fromId),t=c.entities.find(e=>e.id===r.toId),support=(r.evidenceIds||[]).map(id=>c.evidence.find(e=>e.id===id)).filter(Boolean);return `<div class="case-row"><div><strong>${esc(f?.label||'Unknown')} → ${esc(r.label)} → ${esc(t?.label||'Unknown')}</strong><span class="small muted">${esc(r.mode)} · ${support.length} supporting evidence item${support.length===1?'':'s'}</span>${support.length?`<details><summary class="small" style="cursor:pointer;margin-top:6px">Show support</summary><ul>${support.map(e=>`<li>${esc(e.title)}</li>`).join('')}</ul></details>`:''}</div><button class="btn small danger" data-delete-relation="${r.id}">Delete</button></div>`;}
function timelineTab(c){const dated=c.evidence.filter(e=>e.sourceEventDate).sort((a,b)=>a.sourceEventDate.localeCompare(b.sourceEventDate)),undated=c.evidence.filter(e=>!e.sourceEventDate);return `<div class="grid two"><div class="card"><h3>Historical timeline</h3><p class="small muted">Only source-event dates are used. Retrieval time never substitutes for event time.</p>${dated.length?`<div class="timeline">${dated.map(e=>`<div class="timeline-item"><strong>${esc(fmtDay(e.sourceEventDate))}</strong><p style="margin:3px 0">${esc(e.title)}</p><span class="small muted">${esc(e.subject)} · ${e.sourceUrl?`<a href="${esc(e.sourceUrl)}" target="_blank">citation ↗</a>`:esc(e.originalFilename||'user supplied')}</span></div>`).join('')}</div>`:`<div class="empty">No dated evidence yet.</div>`}</div><div class="card"><h3>Undated evidence</h3><p class="small muted">These items remain separate until a source event date is known.</p>${undated.length?`<div class="ledger">${undated.map(e=>`<div class="evidence-row"><div><strong>${esc(e.title)}</strong><p class="small muted">${esc(e.subject)}</p></div></div>`).join('')}</div>`:`<div class="empty">Nothing undated.</div>`}</div></div>`;}
function questionsTab(c){const evOpts=c.evidence.map(e=>`<option value="${e.id}">${esc(e.title)}</option>`).join(''),gaps=gapSuggestions(c);return `<div class="grid two"><div class="card"><h3>Add question / task / contradiction</h3><form id="questionForm" class="form-grid"><label>Type<select name="type"><option value="question">question</option><option value="task">task</option><option value="contradiction">contradiction</option></select></label><label class="full">Text<textarea name="text" required></textarea></label><label class="full">Linked evidence<select name="evidenceIds" multiple size="4">${evOpts}</select></label><div class="full"><button class="btn primary" type="submit">Add item</button></div></form></div><div class="card"><h3>Deterministic proof gaps</h3><p class="small muted">Rules-based suggestions from current case state; no fake AI inference.</p>${gaps.length?`<ul>${gaps.map(g=>`<li>${esc(g)}</li>`).join('')}</ul>`:`<div class="empty">No structural gaps detected by current rules.</div>`}</div></div><div class="card"><h3>Open work & contradictions</h3>${c.questions.length?`<div class="question-list">${c.questions.map(q=>questionRow(c,q)).join('')}</div>`:`<div class="empty">No questions or tasks yet.</div>`}</div>`;}
function questionRow(c,q){return `<div class="case-row"><div><div class="actions"><span class="badge ${q.type==='contradiction'?'error':q.type==='task'?'warn':'teal'}">${esc(q.type)}</span><span class="badge ${q.resolved?'ok':'warn'}">${q.resolved?'resolved':'open'}</span></div><strong style="margin-top:6px">${esc(q.text)}</strong>${q.resolved&&q.resolution?`<span class="small muted">Resolution: ${esc(q.resolution)}</span>`:''}</div><div class="actions">${q.resolved?`<button class="btn small ghost" data-reopen-q="${q.id}">Reopen</button>`:`<button class="btn small primary" data-resolve-q="${q.id}">Resolve</button>`}<button class="btn small danger" data-delete-q="${q.id}">Delete</button></div></div>`;}

function sourcesView(){
  const rows=[
    ['GitHub','Live','Exact public user profile metadata for username checks.'],
    ['GitLab','Live','Exact public user profile metadata for username checks.'],
    ['Cloudflare DNS + Google DNS fallback','Live','A/AAAA/MX/TXT/DMARC public DNS; email checks inspect the domain, not mailbox existence.'],
    ['RDAP domain','Live','Public domain registration/status context from RDAP.'],
    ['RIPEstat','Live','IP routing and origin ASN context; not person attribution or precise geolocation.'],
    ['RDAP IP','Live','Public IP allocation/registry context; not device or person attribution.'],
    ['Breach provider','Not configured','No breach conclusion is claimed until server-side provider access is configured.'],
    ['Phone ownership provider','Not configured','Phone numbers are normalized only; no owner attribution is performed.']
  ];
  return `<section class="section"><div class="card"><div class="section-head"><div><div class="eyebrow">PROVIDER MATRIX</div><h2>Coverage without pretending</h2><p class="muted">A missing provider stays missing. A failed lookup stays failed. TraceForge does not turn silence into a conclusion.</p></div></div><table class="source-table"><thead><tr><th>Source</th><th>Status</th><th>Scope / limitation</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r[0])}</strong></td><td><span class="badge ${r[1]==='Live'?'ok':'warn'}">${esc(r[1])}</span></td><td>${esc(r[2])}</td></tr>`).join('')}</tbody></table></div></section><section class="section"><div class="card inset"><strong>Evidence contract</strong><p class="small muted" style="margin-bottom:0">Every fetched evidence line carries provider, observation, checked time, source URL and limitation. Manual evidence remains labeled as user supplied. Shared identifiers never auto-merge identities.</p></div></section>`;
}
function modalHtml(){return '';}

